source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem 'faker', '~> 2.18.0'
gem 'rspec', :require => false #This means that we don’t want to require the gem rspec when we run bundle install but we do want to install it.


group :development, :test do
  # Gems for development and test environments
  gem 'colorize', '~> 0.8.1'

end


gemspec
